### PR TITLE
chore: auto-merge renovate pull requests

### PR DESCRIPTION
**Pull request by yftacherzog**

### CODE REVIEW

**Comment by yftacherzog** [comment]
@gbenhaim as we now have plenty of repos with frequent renovate updates, I think we should have them merged automatically. I'd like to have it tested on this repo.

Can you take a look to see if the configs make sense?

**Comment by avi-biton** [comment]
Any specific reason to use this repository?

**Comment by yftacherzog** [comment]
> Any specific reason to use this repository?

As far as I understand, changes here are not affecting anyone in the immediate time frame, so I thought it could be a good pick.

**Comment by avi-biton** [comment]
lgtm, but I am not familiar with Renovate configuration

**Comment by yftacherzog** [comment]
@gbenhaim can you take a look?

**Comment by avi-biton** [comment]
@yftacherzog Lets merge it and see the results, we can always revert

**Pull request merged**
